# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BasicPlaybackSampleApp' do

source 'https://github.com/ooyala/ios-sdk-podspecs.git'
pod 'OoyalaSDK', '~> 3.5.0'

end

target 'BasicPlaybackSampleAppSource' do

end

