# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CocoaPodsSampleApp' do

source 'https://github.com/ooyala/ios-sdk-podspecs.git'
  pod 'OoyalaSDK'

end

target 'CocoaPodsSampleAppSource' do

end
